### ISSUE TITLE
[BUG] Links for Timezone Calculator project are broken

### ISSUE THREAD

**Issue by SashoStoichkov** [nhcarrigan/nhcarrigan.github.io#113]
# Bug Report

## Describe the bug

Links for Timezone Calculator project are broken
- `View project` redirects to empty page with this url https://www.nhcarrigan.com/
![image](https://user-images.githubusercontent.com/24972335/109411022-9e768980-79a7-11eb-88f3-f1dd007a49f7.png)

- `View code` goes to a `404` GitHub repo
![image](https://user-images.githubusercontent.com/24972335/109411045-d978bd00-79a7-11eb-9a81-c02d0c64cd65.png)

## Screenshots (video)

https://www.loom.com/share/534de7036d234993bee6a9c5bde8b999

**Comment by nhcarrigan** [comment]
Ah - because the repo is `timezone-chart`.

The links are located in `src/assets/data/Projects.ts` and need to be updated to use `timezone-chart` instead of `timezone-calculator`. 

An issue with the _help wanted_ or _good first issue_ label is open for contribution. The first comprehensive PR created will be reviewed and merged.

If you would like to contribute, please review our [contributing documentation](../blob/main/CONTRIBUTING.md).

If you have any issues with contributing, we are available to help in our [chat server](http://chat.nhcarrigan.com).
