### ISSUE TITLE
[BUG] Wrong link for BattleSnake project

### ISSUE THREAD

**Issue by SashoStoichkov** [nhcarrigan/nhcarrigan.github.io#131]
# Bug Report

## Describe the bug

The link for the BattleSnake project under `View project` redirects to `https://forum.nhcarrigan.com/`. This page however is unreachable.

## Expected behavior

Maybe these links should redirect as follows:
- `View project` -> https://play.battlesnake.com/u/nhcarrigan/becca-lyria/
- `View code` -> https://github.com/nhcarrigan/battlesnake

## Screenshots

![image](https://user-images.githubusercontent.com/24972335/110252884-3c61e980-7f90-11eb-84f7-4aa2b784d96c.png)
![image](https://user-images.githubusercontent.com/24972335/110252894-44218e00-7f90-11eb-8682-2142f23b4c52.png)

**Comment by nhcarrigan** [comment]
Whoops! Missed one!

**Comment by SashoStoichkov** [comment]
Wow the response time was amazing ⚡

**Comment by nhcarrigan** [comment]
Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Within the `src/assets/data/Projects.ts` file,
  - Modifying the `title: 'Battlesnake'` object:
    - Change the `liveUrl` value to `'https://play.battlesnake.com/u/nhcarrigan/becca-lyria/'`.
    - Change the `codeUrl` value to `'https://github.com/nhcarrigan/battlesnake`.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, let us know and we can assign you to it. Please note that we typically accept the first PR to comprehensively resolve the issue (as long as it meets our contributing guidelines) regardless of who is assigned to an issue.

Happy contributing.

**Comment by shubhamayush12** [comment]
Hlo I am new to the open source world but being a beginner can I try to fix this issue .

**Comment by SashoStoichkov** [comment]
Yep go ahead 👍🏻

**Comment by shubhamayush12** [comment]
But I am not able to find src/assets/data/Projects.ts file. Can you help me

**Comment by SashoStoichkov** [comment]
https://github.com/nhcarrigan/nhcarrigan.github.io/blob/main/src/assets/data/Projects.ts

**Comment by SashoStoichkov** [comment]
And also make sure you read the [contributing guidelines](https://github.com/nhcarrigan/nhcarrigan.github.io/blob/main/CONTRIBUTING.md)

**Comment by shubhamayush12** [comment]
I have created the pull request kindly review it
